# Where things are
source:       .
destination:  ./_site
plugins_dir:      ./_plugins
layouts_dir:      ./_layouts
gems: [jekyll-paginate]
paginate:     8

# Handling Reading
safe:         false
include:      [".htaccess"]
exclude:      []
keep_files:   [".git", ".svn"]
encoding:     "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"
textile_ext:  "textile"

# Filtering Content
show_drafts:  null
limit_posts:  0
future:       true
unpublished:  false

# Conversion
markdown:     kramdown
highlighter:  pygments
lsi:          false
excerpt_separator: "\n\n"

# Serving
detach:       false
port:         4000
host:         127.0.0.1
baseurl:      "" # does not include hostname

# Outputting
permalink:     date
paginate_path: /page:num
timezone:      null


#Site config
title: blog
description: geleeq's blog.
keywords: geleeq blog
url: http://geleeq.github.io/blog
feed: /atom.xml
favicon: http://jekyllrb.com/favicon.png

#Nav config
nav:
  - text: 首页
    url: /index.html
  - text: 分类目录 
    url: /categories.html
  - text: 文章归档
    url: /archives.html
  - text: 联系我
    url: /contact.html
  - text: 友情链接
    url: /links.html

#Author config
author:
    name: 力神
    email: ge.liqing@zte.com.cn
#http://tp2.sinaimg.cn/1832671293/180/40020872447/1
    imageLink: http://ww4.sinaimg.cn/mw690/bfb36362tw1ehi7432bs9j20dc0hswgn.jpg
    simpleIntro: 我是「力神」葛立青 tag: java 福州 ZTE-nubia 服务端开发 
    detailIntro:
      <p>七年前，我读高中，同桌是个安静漂亮的姑娘，很是喜欢我，但也许是情商过低的原因，我对她熟视无睹，我唯一的爱好就是玩dota…
我当时非常喜欢影魔，不厌其烦的向她灌输着大影魔如何厉害，我的技术如何牛逼，虽然她听不懂，但是还是安安静静地看着我，眼含笑意。
高三毕业那天，我送了一张绝版大影魔的明信片给她，她满心欢喜，毕竟三年来我第一次送她东西………
时光荏苒，当我已经玩这款游戏的过得第七个夏天，慢慢的，玩的人越来越少，当年的一起玩的朋友都已经不在，我玩的时间也慢慢变少，我大学毕业、工作、应酬、整日在推杯换盏中虚与委蛇，不知不觉很多人和事情都已淡忘，只有玩dota的时候偶尔也会想起当年头同桌的她。
去年春节回家，无事可做，决定去网吧玩会，结果没玩几把发现意识还在，但反应跟不上了，索性看别人玩，看了一会，视线被一个孩子吸引住了了，感觉这孩子走位意识，技术打打都很有套路，趁那孩子赢了的时候，我主动过去和他攀谈起来。
“玩的不错嘛，几岁了？”
“5岁了”
“技术这么好，平时没少玩吧？”
“平时没怎么玩，我爸爸不喜欢我玩，但我还是喜欢。”
我一愣，顿时接不上话，气氛显得有些沉闷，我换了个话题。
“你喜欢dota？”
“恩”
“那你最喜欢哪个角色？”
“影魔，刷的快爆发高可以秀不解释！”他不假思索的回答到。
“嘿，你也喜欢玩影魔”我顿时来了兴致。
他骄傲的回答:“当然了，我妈妈有一张绝版的影魔明信片，她说影魔是最厉害的…”
夕阳的余光透过窗户照在他满含笑意的脸庞，就像她当年那样。有些人，有些事，一旦错过就是错过，不再擦肩，也没有回头，虽然，岁月带走了心中最美好的曾经。
但是我并不伤心，因为，
这          这          这
都          都          都   
是          是          是
我          我          我
编          编          编
的          的          的
。          。          。
重要的事情要说三遍</p>


#Follow me, you can choose your icon by http://fortawesome.github.io/Font-Awesome/icons/#brand
follow:
  - class: icon-rss
    url: /atom.xml
  - class: icon-weibo
    url: http://weibo.com/geleeq
  - class: icon-renren
    url: http://renren.com
  - class: icon-github-alt
    url: http://github.com/GeLeeq
  - class: icon-twitter
    url: http://twitter.com/
  - class: icon-google-plus
    url: http://google.com

#Links
customLinks:
  - item:
    - text: geleeq@github
      url: https://github.com/GeLeeq
    - text: Jekyll
      url: http://jekyllrb.com
    - text: Jekyll Theme
      url: http://www.zhanxin.info/themes.html
    message: Friends
  - item:
    - text: Font Awesome
      url: http://fortawesome.github.io/Font-Awesome/
    - text: Google Font
      url: http://www.google.com/fonts/
    - text: jQuery
      url: http://jquery.com/
    message: 其他相关链接

#googleAnaly, your id link UA-12345678-X
googleAnaly:
  config: false
  id: UA-40169250-1

#comment config
disqus:
  config: false
  id: piznblog

duoshuo:
  config: true
  id: geleeq
